// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBWy-c_XNc924LqxzEdIjItT14oooHGrQ',
    appId: '1:1013910908907:web:31ef06bf56a36b44f033ae',
    messagingSenderId: '1013910908907',
    projectId: 'fruit-hub-c5794',
    authDomain: 'fruit-hub-c5794.firebaseapp.com',
    storageBucket: 'fruit-hub-c5794.firebasestorage.app',
    measurementId: 'G-SDQZBGKKFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaw5_fdqWFhLNu4L0EnoBD_9-RYF2YCVI',
    appId: '1:1013910908907:android:55af4dcbfbbbf042f033ae',
    messagingSenderId: '1013910908907',
    projectId: 'fruit-hub-c5794',
    storageBucket: 'fruit-hub-c5794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7x0bBVBWKJ_F2XcL379PZ6VHCo8ZqPEA',
    appId: '1:1013910908907:ios:e582d6b00731026cf033ae',
    messagingSenderId: '1013910908907',
    projectId: 'fruit-hub-c5794',
    storageBucket: 'fruit-hub-c5794.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
